import streamlit as st
import pandas as pd
import plotly.express as px

# 1. Page Configuration
st.set_page_config(page_title="Zebrafish 3D Morphometry", layout="wide")

st.title("🔬 Zebrafish 3D Morphometry Suite")
st.markdown("Developed for quantitative analysis of nuclei distribution in zebrafish embryos.")

# 2. Sidebar for Data Upload
st.sidebar.header("Data Input")
uploaded_file = st.sidebar.file_uploader("Upload 'zebrafish_nuclei_data.csv'", type="csv")

if uploaded_file:
    df = pd.read_csv(uploaded_file)
    
    # 3. Key Metrics Row
    st.subheader("📊 Quantitative Summary")
    m1, m2, m3, m4 = st.columns(4)
    m1.metric("Total Nuclei Count", len(df))
    m2.metric("Avg Volume (voxels)", f"{df['volume_voxels'].mean():.1f}")
    
    if 'centroid-0' in df.columns:
        z_range = df['centroid-0'].max() - df['centroid-0'].min()
        m3.metric("Z-Depth Span", f"{z_range:.1f}")
    
    if 'nearest_neighbor_dist' in df.columns:
        m4.metric("Mean NN Distance", f"{df['nearest_neighbor_dist'].mean():.2f}")

    st.markdown("---")

    # 4. 3D Visualization and Analysis
    col_left, col_right = st.columns([2, 1])

    with col_left:
        st.subheader("📍 3D Spatial Distribution")
        # Use simple scatter_3d with a dark background to force contrast
        fig_3d = px.scatter_3d(
            df, x='centroid-2', y='centroid-1', z='centroid-0',
            color='volume_voxels',
            template="plotly_dark"  # Dark theme often renders better on cloud
        )
        fig_3d.update_traces(marker=dict(size=4)) # Smaller markers for better visibility
        st.plotly_chart(fig_3d, use_container_width=True)

    with col_right:
        st.subheader("📈 Depth Profile")
        # Standard bar histogram
        fig_z = px.histogram(
            df, x="centroid-0", 
            nbins=15, 
            color_discrete_sequence=['#00CC96'],
            template="plotly_white"
        )
        st.plotly_chart(fig_z, use_container_width=True)

    # 5. Raw Data Inspection
    with st.expander("🔍 Inspect Raw Morphometric Data"):
        st.dataframe(df)

else:
    st.info("👋 Welcome! Please upload the CSV generated by your analysis script to view the 3D morphometry.")
    # Using a high-quality Wikimedia image that is guaranteed to load
    st.image("https://upload.wikimedia.org/wikipedia/commons/thumb/a/ac/Zebrafish_embryo_72h.jpg/800px-Zebrafish_embryo_72h.jpg", caption="Zebrafish Embryo (72hpf)")
