import streamlit as st
import pandas as pd
import plotly.express as px

# 1. Page Configuration
st.set_page_config(page_title="Zebrafish 3D Morphometry", layout="wide")

st.title("🔬 Zebrafish 3D Morphometry Suite")
st.markdown("""
    *Developed for quantitative analysis of nuclei distribution in zebrafish embryos.*
    ---
""")

# 2. Sidebar for Data Upload
st.sidebar.header("Data Input")
uploaded_file = st.sidebar.file_uploader("Upload 'zebrafish_nuclei_data.csv'", type="csv")

if uploaded_file:
    df = pd.read_csv(uploaded_file)
    
    # 3. Key Metrics Row
    st.subheader("📊 Quantitative Summary")
    m1, m2, m3, m4 = st.columns(4)
    m1.metric("Total Nuclei Count", len(df))
    m2.metric("Avg Volume (voxels)", f"{df['volume_voxels'].mean():.1f}")
    
    if 'centroid-0' in df.columns:
        z_range = df['centroid-0'].max() - df['centroid-0'].min()
        m3.metric("Z-Depth Span", f"{z_range:.1f}")
    
    if 'nearest_neighbor_dist' in df.columns:
        m4.metric("Mean NN Distance", f"{df['nearest_neighbor_dist'].mean():.2f}")

    st.markdown("---")

    # 4. 3D Visualization and Analysis
    col_left, col_right = st.columns([2, 1])

    with col_left:
        st.subheader("📍 3D Spatial Distribution")
        fig_3d = px.scatter_3d(
            df, x='centroid-2', y='centroid-1', z='centroid-0',
            color='volume_voxels', 
            opacity=0.8,
            color_continuous_scale='Viridis'
        )
        # Force a white background for visibility
        fig_3d.update_layout(scene=dict(bgcolor='white'), margin=dict(l=0, r=0, b=0, t=0))
        st.plotly_chart(fig_3d, use_container_width=True)

    with col_right:
        st.subheader("📈 Depth Profile")
        fig_z = px.histogram(
            df, x="centroid-0", 
            nbins=20, 
            title="Nuclei Count vs Depth",
            color_discrete_sequence=['#00CC96']
        )
        fig_z.update_layout(plot_bgcolor='white')
        st.plotly_chart(fig_z, use_container_width=True)

    # 5. Raw Data Inspection
    with st.expander("🔍 Inspect Raw Morphometric Data"):
        st.dataframe(df)

else:
    st.info("👋 Welcome! Please upload the CSV generated by your analysis script to view the 3D morphometry.")
    # Professional Biology Image from a reliable source
    st.image("https://images.lifescience.net/api/v1/images/597858c7e4b09c4d9f6e1f3a/content", caption="Zebrafish Embryo Imaging")
